version: "3.9"

services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oab-scraper
    command: uvicorn scraper.main:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oab-agent
    command: sh -c "sleep 5 && python agent/main.py"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - scraper
    stdin_open: true
    tty: true